// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP0_uDsGm1oBbGUiiJX-cLOeBwS8V5JNU',
    appId: '1:329569516510:web:bbee7b56ad49223b11fb4f',
    messagingSenderId: '329569516510',
    projectId: 'pixora-845b7',
    authDomain: 'pixora-845b7.firebaseapp.com',
    storageBucket: 'pixora-845b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAJoof8kDSQXRl0dG_qpVVBu7cgvnkRg',
    appId: '1:329569516510:android:39fe3286d3e29e4311fb4f',
    messagingSenderId: '329569516510',
    projectId: 'pixora-845b7',
    storageBucket: 'pixora-845b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2eSCaqHFHLSDzOG5ORZcIxFK-_4bgz_o',
    appId: '1:329569516510:ios:371e1349d43a412011fb4f',
    messagingSenderId: '329569516510',
    projectId: 'pixora-845b7',
    storageBucket: 'pixora-845b7.firebasestorage.app',
    iosBundleId: 'com.example.pixora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2eSCaqHFHLSDzOG5ORZcIxFK-_4bgz_o',
    appId: '1:329569516510:ios:371e1349d43a412011fb4f',
    messagingSenderId: '329569516510',
    projectId: 'pixora-845b7',
    storageBucket: 'pixora-845b7.firebasestorage.app',
    iosBundleId: 'com.example.pixora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP0_uDsGm1oBbGUiiJX-cLOeBwS8V5JNU',
    appId: '1:329569516510:web:dcb030a21e93093a11fb4f',
    messagingSenderId: '329569516510',
    projectId: 'pixora-845b7',
    authDomain: 'pixora-845b7.firebaseapp.com',
    storageBucket: 'pixora-845b7.firebasestorage.app',
  );

}